import { addDays } from "date-fns";

export const mockSchedules = [
  // Today's schedules
  {
    id: "sched1",
    employee_id: "emp1",
    employee_name: "Sweta Kumari",
    position: "Floor Manager",
    date: new Date(),
    shift: "morning",
    location: "Main Office",
  },
  {
    id: "sched2",
    employee_id: "emp1",
    employee_name: "Sweta Kumari",
    position: "Floor Manager",
    date: new Date(),
    shift: "evening",
    location: "Main Office",
  },
  {
    id: "sched3",
    employee_id: "emp2",
    employee_name: "Abhishek Roy",
    position: "Floor Manager",
    date: new Date(),
    shift: "night",
    location: "Main Office",
  },
  {
    id: "sched4",
    employee_id: "emp3",
    employee_name: "Ritika Khanna",
    position: "RAs",
    date: new Date(),
    shift: "morning",
    location: "Wing A",
  },
  {
    id: "sched5",
    employee_id: "emp5",
    employee_name: "Anshul Soni",
    position: "RAs",
    date: new Date(),
    shift: "evening",
    location: "Wing B",
  },
  {
    id: "sched6",
    employee_id: "emp6",
    employee_name: "Bhavya",
    position: "Technicians",
    date: new Date(),
    shift: "morning",
    location: "Lab 1",
  },
  {
    id: "sched7",
    employee_id: "emp7",
    employee_name: "Mohammed Arshad Ahammed",
    position: "Technicians",
    date: new Date(),
    shift: "day",
    location: "Lab 2",
  },
  {
    id: "sched8",
    employee_id: "emp8",
    employee_name: "A.M.G.S.TEJENDRA NAIDU",
    position: "Subjects",
    date: new Date(),
    shift: "morning",
    location: "Room 101",
  },
  {
    id: "sched9",
    employee_id: "emp9",
    employee_name: "Bhaskar Choudhary",
    position: "Subjects",
    date: new Date(),
    shift: "overnight",
    location: "Room 102",
  },

  // Tomorrow's schedules
  {
    id: "sched10",
    employee_id: "emp2",
    employee_name: "Abhishek Roy",
    position: "Floor Manager",
    date: addDays(new Date(), 1),
    shift: "morning",
    location: "Main Office",
  },
  {
    id: "sched11",
    employee_id: "emp3",
    employee_name: "Ritika Khanna",
    position: "RAs",
    date: addDays(new Date(), 1),
    shift: "evening",
    location: "Wing A",
  },
  {
    id: "sched12",
    employee_id: "emp5",
    employee_name: "Anshul Soni",
    position: "RAs",
    date: addDays(new Date(), 1),
    shift: "night",
    location: "Wing B",
  },
  {
    id: "sched13",
    employee_id: "emp7",
    employee_name: "Mohammed Arshad Ahammed",
    position: "Technicians",
    date: addDays(new Date(), 1),
    shift: "day",
    location: "Lab 2",
  },
  {
    id: "sched14",
    employee_id: "emp8",
    employee_name: "A.M.G.S.TEJENDRA NAIDU",
    position: "Subjects",
    date: addDays(new Date(), 1),
    shift: "overnight",
    location: "Room 101",
  },

  // Next week's schedules
  {
    id: "sched15",
    employee_id: "emp1",
    employee_name: "Sweta Kumari",
    position: "Floor Manager",
    date: addDays(new Date(), 7),
    shift: "morning",
    location: "Main Office",
  },
  {
    id: "sched16",
    employee_id: "emp4",
    employee_name: "Vidyun",
    position: "RAs",
    date: addDays(new Date(), 7),
    shift: "evening",
    location: "Wing C",
  },
  {
    id: "sched17",
    employee_id: "emp6",
    employee_name: "Bhavya",
    position: "Technicians",
    date: addDays(new Date(), 7),
    shift: "night",
    location: "Lab 1",
  },
  {
    id: "sched18",
    employee_id: "emp9",
    employee_name: "Bhaskar Choudhary",
    position: "Subjects",
    date: addDays(new Date(), 7),
    shift: "day",
    location: "Room 102",
  },
  {
    id: "sched19",
    employee_id: "emp10",
    employee_name: "Karthikeyan",
    position: "Subjects",
    date: addDays(new Date(), 7),
    shift: "overnight",
    location: "Room 103",
  },
];

export const mockEmployees = [
  {
    id: "emp1",
    employee_id: "EMP001",
    name: "Sweta Kumari",
    position: "Floor Manager",
    onLeave: false,
    phone: "9876543210",
    email: "sweta.k@example.com",
    orgId: "ORG001",
    joinDate: "2020-05-15",
    status: "active",
    createdAt: "2020-05-15T00:00:00Z",
    updatedAt: "2023-01-10T00:00:00Z",
  },
  {
    id: "emp2",
    employee_id: "EMP002",
    name: "Abhishek Roy",
    position: "Floor Manager",
    onLeave: false,
    phone: "8765432109",
    email: "abhishek.r@example.com",
    orgId: "ORG001",
    joinDate: "2019-11-20",
    status: "active",
    createdAt: "2019-11-20T00:00:00Z",
    updatedAt: "2023-02-15T00:00:00Z",
  },
  {
    id: "emp3",
    employee_id: "EMP003",
    name: "Ritika Khanna",
    position: "RAs",
    onLeave: false,
    phone: "7654321098",
    email: "ritika.k@example.com",
    orgId: "ORG001",
    joinDate: "2021-03-10",
    status: "active",
    createdAt: "2021-03-10T00:00:00Z",
    updatedAt: "2023-03-05T00:00:00Z",
  },
  {
    id: "emp4",
    employee_id: "EMP004",
    name: "Vidyun",
    position: "RAs",
    onLeave: true,
    phone: "6543210987",
    email: "vidyun@example.com",
    orgId: "ORG001",
    joinDate: "2021-07-22",
    status: "active",
    createdAt: "2021-07-22T00:00:00Z",
    updatedAt: "2023-04-01T00:00:00Z",
  },
  {
    id: "emp5",
    employee_id: "EMP005",
    name: "Anshul Soni",
    position: "RAs",
    onLeave: false,
    phone: "5432109876",
    email: "anshul.s@example.com",
    orgId: "ORG001",
    joinDate: "2022-01-05",
    status: "active",
    createdAt: "2022-01-05T00:00:00Z",
    updatedAt: "2023-01-20T00:00:00Z",
  },
  {
    id: "emp6",
    employee_id: "EMP006",
    name: "Bhavya",
    position: "Technicians",
    onLeave: false,
    phone: "4321098765",
    email: "bhavya@example.com",
    orgId: "ORG001",
    joinDate: "2020-09-12",
    status: "active",
    createdAt: "2020-09-12T00:00:00Z",
    updatedAt: "2023-02-28T00:00:00Z",
  },
  {
    id: "emp7",
    employee_id: "EMP007",
    name: "Mohammed Arshad Ahammed",
    position: "Technicians",
    onLeave: false,
    phone: "3210987654",
    email: "arshad.m@example.com",
    orgId: "ORG001",
    joinDate: "2021-05-30",
    status: "active",
    createdAt: "2021-05-30T00:00:00Z",
    updatedAt: "2023-03-15T00:00:00Z",
  },
  {
    id: "emp8",
    employee_id: "EMP008",
    name: "A.M.G.S.TEJENDRA NAIDU",
    position: "Subjects",
    onLeave: false,
    phone: "2109876543",
    email: "tejendra.n@example.com",
    orgId: "ORG001",
    joinDate: "2022-03-18",
    status: "active",
    createdAt: "2022-03-18T00:00:00Z",
    updatedAt: "2023-01-25T00:00:00Z",
  },
  {
    id: "emp9",
    employee_id: "EMP009",
    name: "Bhaskar Choudhary",
    position: "Subjects",
    onLeave: false,
    phone: "1098765432",
    email: "bhaskar.c@example.com",
    orgId: "ORG001",
    joinDate: "2022-06-10",
    status: "active",
    createdAt: "2022-06-10T00:00:00Z",
    updatedAt: "2023-02-10T00:00:00Z",
  },
  {
    id: "emp10",
    employee_id: "EMP010",
    name: "Karthikeyan",
    position: "Subjects",
    onLeave: true,
    phone: "0987654321",
    email: "karthikeyan@example.com",
    orgId: "ORG001",
    joinDate: "2021-12-05",
    status: "active",
    createdAt: "2021-12-05T00:00:00Z",
    updatedAt: "2023-04-05T00:00:00Z",
  },
];
